services:
  web:
    build: .
    container_name: nexngn
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
    expose:
      - "80"
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nexngn.rule=Host(`nexngn.com`) || Host(`www.nexngn.com`)"
      - "traefik.http.routers.nexngn.entrypoints=websecure"
      - "traefik.http.routers.nexngn.tls=true"
      - "traefik.http.services.nexngn.loadbalancer.server.port=80"

networks:
  traefik-proxy:
    external: true
